#!/usr/bin/env python3
"""Generate a development ML-DSA-65 key and embed only its public key in Bootloader.

The generated secret key is for local validation only. Production release keys must
be created and held by an offline signer or HSM.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path

from ota_format import ML_DSA_65_PUBLIC_KEY_SIZE, ML_DSA_65_SECRET_KEY_SIZE, encode_identity


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent


def c_array(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        rows.append("    " + ", ".join(f"0x{byte:02X}U" for byte in data[offset:offset + 12]))
    return f"const uint8_t {name}[{len(data)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="生成开发发布者ML-DSA-65密钥")
    parser.add_argument("--publisher", default="UPQC-PUBLISHER01")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    tool = SCRIPT_DIR / "mldsa_tool.exe"
    keys = SCRIPT_DIR / "keys"
    public_path = keys / "dev_publisher_pk.bin"
    secret_path = keys / "dev_publisher_sk.bin"
    output_c = PROJECT_ROOT / "bootloader" / "Core" / "Src" / "trusted_publisher_key.c"

    if not tool.exists():
        raise SystemExit("缺少mldsa_tool.exe，请先运行build_mldsa_tool.ps1")
    keys.mkdir(exist_ok=True)
    if args.force or not public_path.exists() or not secret_path.exists():
        subprocess.run([str(tool), "keygen", str(public_path), str(secret_path)], check=True)

    public_key = public_path.read_bytes()
    secret_key = secret_path.read_bytes()
    if len(public_key) != ML_DSA_65_PUBLIC_KEY_SIZE or len(secret_key) != ML_DSA_65_SECRET_KEY_SIZE:
        raise SystemExit("开发密钥长度错误")

    publisher_id = encode_identity(args.publisher, 16, "publisher")
    key_id = hashlib.sha256(public_key).digest()[:16]
    source = (
        "/* Auto-generated by pc_tool/provision_dev_publisher.py. */\n"
        "#include \"trusted_publisher.h\"\n\n"
        + c_array("g_trusted_publisher_id", publisher_id) + "\n"
        + c_array("g_trusted_publisher_key_id", key_id) + "\n"
        + c_array("g_trusted_publisher_public_key", public_key)
    )
    output_c.write_text(source, encoding="ascii", newline="\n")

    print(f"[KEY] publisher : {args.publisher}")
    print(f"[KEY] key_id    : {key_id.hex()}")
    print(f"[KEY] public    : {public_path}")
    print(f"[KEY] secret    : {secret_path} (DEVELOPMENT ONLY)")
    print(f"[KEY] embedded  : {output_c}")


if __name__ == "__main__":
    main()
